apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      lifecycle:
        preStop:
          exec:
            command: ["sleep", "30"]
            # some other command to ignore requests
            # some other command for timeout 